name: mobile-wireguard-stack

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - "./config/wg0.conf:/config/wg_confs/wg0.conf:ro"
      # - "/lib/modules:/lib/modules:ro" # for kernel modules
    ports:
      # anything that wants to use the wireguard network must expose ports here

      # qBittorrent
      - "127.0.0.1:37551:37551"

      # Dante
      - "127.0.0.1:1080:1080"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    healthcheck:
      test: ["CMD-SHELL", "wg show wg0 | grep -q 'latest handshake'"]

  dante:
    image: vimagick/dante
    container_name: dante
    network_mode: service:wireguard
    volumes:
      - "./config/sockd.conf:/etc/dante/sockd.conf:ro"
    tmpfs:
      - /run
    depends_on:
      wireguard:
        condition: service_healthy

    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbittorrent
    environment:
      WEBUI_PORT: "${QBITTORRENT_WEBUI_PORT}"
      TORRENTING_PORT: "${QBITTORRENT_TORRENTING_PORT}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "qbittorrent-config:/config"
      - "${DOWNLOADS_DIR}:/downloads"
    network_mode: "service:wireguard"
    depends_on:
      wireguard:
        condition: service_healthy

  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "jellyfin-config:/config"
      - "${DOWNLOADS_DIR}:/data"
    ports:
      - 8096:8096

volumes:
  qbittorrent-config:
  jellyfin-config:
